import { apiClient } from '@/api/config';
import { AxiosError } from 'axios';
import { API_BASE_URL } from '@/api/config';

// Use centralized API URL from config - no hardcoded fallbacks
const API_URL = API_BASE_URL;

// Interfaces
export interface InventoryMaterial {
  inventory_material_id?: number;
  material_code?: string;  // Auto-generated by backend
  material_name: string;
  brand?: string;
  size?: string;
  category?: string;
  unit: string;
  current_stock: number;
  min_stock_level?: number;
  unit_price: number;
  description?: string;
  is_active?: boolean;
  created_at?: string;
  created_by?: string;
  last_modified_at?: string;
  last_modified_by?: string;
}

export interface InventoryTransaction {
  inventory_transaction_id?: number;
  inventory_material_id: number;
  transaction_type: 'PURCHASE' | 'WITHDRAWAL';
  quantity: number;
  unit_price: number;
  total_amount: number;
  reference_number?: string;
  project_id?: number;
  notes?: string;
  created_at?: string;
  created_by?: string;
}

export interface InternalMaterialRequest {
  request_id?: number;
  request_number?: number;
  project_id: number;
  request_buyer_id: number;
  material_name: string;
  quantity: number;
  brand?: string;
  size?: string;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'DISPATCHED' | 'FULFILLED' | 'PROCUREMENT_INITIATED' | 'send_request' | 'approved' | 'rejected';
  inventory_material_id?: number;
  inventory_transaction_id?: number;
  approved_by?: string;
  approved_at?: string;
  expected_delivery_date?: string;
  dispatch_date?: string;
  actual_delivery_date?: string;
  rejected_by?: string;
  rejected_at?: string;
  rejection_reason?: string;
  notes?: string;
  request_send?: boolean;
  created_at?: string;
  created_by?: string;
  last_modified_at?: string;
  last_modified_by?: string;
}

class InventoryService {
  private getAuthHeader() {
    return {
      'Authorization': `Bearer ${localStorage.getItem('access_token')}`,
      'Content-Type': 'application/json'
    };
  }

  // ==================== INVENTORY MATERIAL METHODS ====================

  /**
   * Create a new inventory material
   */
  async createInventoryItem(material: Omit<InventoryMaterial, 'inventory_material_id'>): Promise<InventoryMaterial> {
    try {
      const response = await apiClient.post(
        `/add_item_inventory`,
        material,
        { headers: this.getAuthHeader() }
      );
      // Backend returns { message: '...', material: {...} }
      return response.data.material;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error creating inventory item:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to create inventory item'
      );
    }
  }

  /**
   * Get all inventory materials
   */
  async getAllInventoryItems(): Promise<InventoryMaterial[]> {
    try {
      const response = await apiClient.get(
        `/all_item_inventory`,
        { headers: this.getAuthHeader() }
      );
      // Backend returns { materials: [...], total: number }
      return response.data.materials || [];
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching inventory items:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch inventory items'
      );
    }
  }

  /**
   * Get a specific inventory item by ID
   */
  async getInventoryItemById(id: number): Promise<InventoryMaterial> {
    try {
      const response = await apiClient.get(
        `/inventory/${id}`,
        { headers: this.getAuthHeader() }
      );
      // Backend returns { material: {...} }
      return response.data.material;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching inventory item:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch inventory item'
      );
    }
  }

  /**
   * Update an inventory item
   */
  async updateInventoryItem(id: number, material: Partial<InventoryMaterial>): Promise<InventoryMaterial> {
    try {
      const response = await apiClient.put(
        `/inventory/${id}`,
        material,
        { headers: this.getAuthHeader() }
      );
      // Backend returns { message: '...', material: {...} }
      return response.data.material;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error updating inventory item:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to update inventory item'
      );
    }
  }

  /**
   * Delete an inventory item
   */
  async deleteInventoryItem(id: number): Promise<{ success: boolean; message: string }> {
    try {
      const response = await apiClient.delete(
        `/inventory/${id}`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error deleting inventory item:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to delete inventory item'
      );
    }
  }

  /**
   * Get transaction history for an item
   */
  async getItemTransactionHistory(id: number): Promise<InventoryTransaction[]> {
    try {
      const response = await apiClient.get(
        `/inventory/${id}/history`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching transaction history:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch transaction history'
      );
    }
  }

  // ==================== INVENTORY TRANSACTION METHODS ====================

  /**
   * Create a new inventory transaction
   */
  async createTransaction(transaction: Omit<InventoryTransaction, 'inventory_transaction_id'>): Promise<InventoryTransaction> {
    try {
      const response = await apiClient.post(
        `/transactions`,
        transaction,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error creating transaction:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to create transaction'
      );
    }
  }

  /**
   * Get all inventory transactions
   */
  async getAllTransactions(): Promise<InventoryTransaction[]> {
    try {
      const response = await apiClient.get(
        `/transactions`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching transactions:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch transactions'
      );
    }
  }

  /**
   * Get a specific transaction by ID
   */
  async getTransactionById(id: number): Promise<InventoryTransaction> {
    try {
      const response = await apiClient.get(
        `/transactions/${id}`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching transaction:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch transaction'
      );
    }
  }

  // ==================== INTERNAL MATERIAL REQUEST METHODS ====================

  /**
   * Create a new internal material request
   */
  async createInternalRequest(request: Omit<InternalMaterialRequest, 'request_id'>): Promise<InternalMaterialRequest> {
    try {
      const response = await apiClient.post(
        `/internal_material_request`,
        request,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error creating internal request:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to create internal request'
      );
    }
  }

  /**
   * Get all internal material requests
   */
  async getAllInternalRequests(): Promise<InternalMaterialRequest[]> {
    try {
      const response = await apiClient.get(
        `/internal_material_requests`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching internal requests:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch internal requests'
      );
    }
  }

  /**
   * Get sent (PENDING) internal requests
   */
  async getSentInternalRequests(): Promise<InternalMaterialRequest[]> {
    try {
      const response = await apiClient.get(
        `/sent_internal_requests`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching sent requests:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch sent requests'
      );
    }
  }

  /**
   * Get a specific internal request by ID
   */
  async getInternalRequestById(id: number): Promise<InternalMaterialRequest> {
    try {
      const response = await apiClient.get(
        `/internal_material/${id}`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching internal request:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch internal request'
      );
    }
  }

  /**
   * Update an internal material request
   */
  async updateInternalRequest(id: number, request: Partial<InternalMaterialRequest>): Promise<InternalMaterialRequest> {
    try {
      const response = await apiClient.put(
        `/internal_material/${id}`,
        request,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error updating internal request:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to update internal request'
      );
    }
  }

  /**
   * Delete an internal material request
   */
  async deleteInternalRequest(id: number): Promise<{ success: boolean; message: string }> {
    try {
      const response = await apiClient.delete(
        `/internal_material/${id}`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error deleting internal request:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to delete internal request'
      );
    }
  }

  /**
   * Send an internal request for approval
   */
  async sendInternalRequest(id: number): Promise<{ success: boolean; message: string }> {
    try {
      const response = await apiClient.get(
        `/internal_material/${id}/send`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error sending internal request:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to send internal request'
      );
    }
  }

  /**
   * Approve an internal request
   */
  async approveInternalRequest(id: number, data?: any): Promise<{ success: boolean; message: string }> {
    try {
      const response = await apiClient.post(
        `/internal_material/${id}/approve`,
        data || {},
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error approving internal request:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to approve internal request'
      );
    }
  }

  /**
   * Reject an internal request
   */
  async rejectInternalRequest(id: number, reason: string): Promise<{ success: boolean; message: string }> {
    try {
      const response = await apiClient.post(
        `/internal_material/${id}/reject`,
        { rejection_reason: reason },
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error rejecting internal request:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to reject internal request'
      );
    }
  }

  /**
   * Dispatch material for a request
   */
  async dispatchMaterial(id: number, data?: any): Promise<{ success: boolean; message: string }> {
    try {
      const response = await apiClient.post(
        `/internal_material/${id}/dispatch`,
        data || {},
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error dispatching material:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to dispatch material'
      );
    }
  }

  /**
   * Check inventory availability for a request
   */
  async checkAvailability(id: number): Promise<any> {
    try {
      const response = await apiClient.get(
        `/internal_material/${id}/check_availability`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error checking availability:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to check availability'
      );
    }
  }

  /**
   * Issue material from inventory
   */
  async issueMaterial(id: number, data?: any): Promise<{ success: boolean; message: string }> {
    try {
      const response = await apiClient.post(
        `/internal_material/${id}/issue_material`,
        data || {},
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error issuing material:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to issue material'
      );
    }
  }

  // ==================== SUMMARY METHODS ====================

  /**
   * Get inventory summary
   */
  async getInventorySummary(): Promise<any> {
    try {
      const response = await apiClient.get(
        `/summary`,
        { headers: this.getAuthHeader() }
      );
      return response.data;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching inventory summary:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch inventory summary'
      );
    }
  }

  /**
   * Get comprehensive dashboard data in a single API call
   */
  async getDashboardData(): Promise<any> {
    try {
      const response = await apiClient.get(
        `/inventory/dashboard`,
        { headers: this.getAuthHeader() }
      );
      return response.data.dashboard;
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('Error fetching dashboard data:', axiosError);
      throw new Error(
        (axiosError.response?.data as any)?.error || 'Failed to fetch dashboard data'
      );
    }
  }
}

export const inventoryService = new InventoryService();